sudo: required

language: bash

services:
  - docker

install:
  - docker build -t intelliops/cronicle .
  - docker run -d -p 127.0.0.1:3012:3012 intelliops/cronicle

script:
  - docker ps -a 
  - sleep 20
  - curl http://localhost:3012 | grep LICENSE
